namespace :db do
  desc 'Criação de UBS'

  task create_ubs: :environment do
    Ub.create(description: "Centro de Saúde Aarão Reis")
    Ub.create(description: "Centro de Saúde Alcides Lins")
    Ub.create(description: "Centro de Saúde Alto Vera Cruz")
    Ub.create(description: "Centro de Saúde Andradas")
    Ub.create(description: "Centro de Saúde Bairro das Industrias")
    Ub.create(description: "Centro de Saúde Barreiro")
    Ub.create(description: "Centro de Saúde Barreiro de Cima")
    Ub.create(description: "Centro de Saúde Betânia")
    Ub.create(description: "Centro de Saúde Boa Vista")
    Ub.create(description: "Centro de Saúde Bom Jesus")
    Ub.create(description: "Centro de Saúde Bonsucesso")
    Ub.create(description: "Centro de Saúde Cabana")
    Ub.create(description: "Centro de Saúde Cachoeirinha")
    Ub.create(description: "Centro de Saúde Cafezal")
    Ub.create(description: "Centro de Saúde California")
    Ub.create(description: "Centro de Saúde Campo Alegre")
    Ub.create(description: "Centro de Saúde Capitão Eduardo")
    Ub.create(description: "Centro de Saúde Carlos Chagas")
    Ub.create(description: "Centro de Saúde Carlos Prates")
    Ub.create(description: "Centro de Saúde Céu Azul")
    Ub.create(description: "Centro de Saúde Cícero Idelfonso")
    Ub.create(description: "Centro de Saúde Cidade Ozanan")
    Ub.create(description: "Centro de Saúde Confisco")
    Ub.create(description: "Centro de Saúde Conjunto Betânia")
    Ub.create(description: "Centro de Saúde Conjunto Paulo VI")
    Ub.create(description: "Centro de Saúde Conjunto Ribeiro de Abreu")
    Ub.create(description: "Centro de Saúde Conjunto Santa Maria")
    Ub.create(description: "Centro de Saúde Copacabana")
    Ub.create(description: "Centro de Saúde Diamante Teixeira Dias")
    Ub.create(description: "Centro de Saúde Dom Bosco")
    Ub.create(description: "Centro de Saúde Dom Cabral")
    Ub.create(description: "Centro de Saúde Dom Joaquim")
    Ub.create(description: "Centro de Saúde Dom Orione")
    Ub.create(description: "Centro de Saúde Eduardo Mauro de Araujo")
    Ub.create(description: "Centro de Saúde Elza Martins da Cruz")
    Ub.create(description: "Centro de Saúde Ermelinda")
    Ub.create(description: "Centro de Saúde Etelvina Carneiro")
    Ub.create(description: "Centro de Saúde Felicidade II")
    Ub.create(description: "Centro de Saúde Floramar I PBH")
    Ub.create(description: "Centro de Saúde Gentil Gomes")
    Ub.create(description: "Centro de Saúde Glória")
    Ub.create(description: "Centro de Saúde Goiânia")
    Ub.create(description: "Centro de Saúde Granja de Freitas")
    Ub.create(description: "Centro de Saúde Guarani")
    Ub.create(description: "Centro de Saúde Havaí")
    Ub.create(description: "Centro de Saúde Heliópolis")
    Ub.create(description: "Centro de Saúde Horto")
    Ub.create(description: "Centro de Saúde Independência")
    Ub.create(description: "Centro de Saúde Itaipujatoba")
    Ub.create(description: "Centro de Saúde Itamarati")
    Ub.create(description: "Centro de Saúde Jaqueline")
    Ub.create(description: "Centro de Saúde Jaqueline II")
    Ub.create(description: "Centro de Saúde Jardim Alvorada")
    Ub.create(description: "Centro de Saúde Jardim Comerciários")
    Ub.create(description: "Centro de Saúde Jardim Europa")
    Ub.create(description: "Centro de Saúde Jardim Felicidade")
    Ub.create(description: "Centro de Saúde Jardim Filadelfia")
    Ub.create(description: "Centro de Saúde Jardim Guanabara")
    Ub.create(description: "Centro de Saúde Jardim Leblon")
    Ub.create(description: "Centro de Saúde Jardim Montanhes")
    Ub.create(description: "Centro de Saúde João Pinheiro")
    Ub.create(description: "Centro de Saúde João XXIII")
    Ub.create(description: "Centro de Saúde Lagoa")
    Ub.create(description: "Centro de Saúde Lajedo")
    Ub.create(description: "Centro de Saúde Lindéia")
    Ub.create(description: "Centro de Saúde Mangueiras")
    Ub.create(description: "Centro de Saúde Mantiqueira")
    Ub.create(description: "Centro de Saúde Marcelo Pontel Gomes")
    Ub.create(description: "Centro de Saúde Marco Antônio de Menezes")
    Ub.create(description: "Centro de Saúde Maria Goretti")
    Ub.create(description: "Centro de Saúde Mariano de Abreu")
    Ub.create(description: "Centro de Saúde Marivanda Baleeiro")
    Ub.create(description: "Centro de Saúde Menino Jesus")
    Ub.create(description: "Centro de Saúde MG20 Monte Azul")
    Ub.create(description: "Centro de Saúde Milionários")
    Ub.create(description: "Centro de Saúde Minas Caixa")
    Ub.create(description: "Centro de Saúde Nazaré")
    Ub.create(description: "Centro de Saúde Noraldino de Lima")
    Ub.create(description: "Centro de Saúde Nossa Senhora Aparecida")
    Ub.create(description: "Centro de Saúde Nossa Senhora de Fátima")
    Ub.create(description: "Centro de Saúde Nova York")
    Ub.create(description: "Centro de Saúde Novo Aarão Reis")
    Ub.create(description: "Centro de Saúde Novo Horizonte")
    Ub.create(description: "Centro de Saúde Olavo Albino Correa")
    Ub.create(description: "Centro de Saúde Oswaldo Cruz")
    Ub.create(description: "Centro de Saúde Ouro Preto")
    Ub.create(description: "Centro de Saúde Padre Eustáquio")
    Ub.create(description: "Centro de Saúde Padre Fernando de Melo")
    Ub.create(description: "Centro de Saúde Padre Joaquim Maia")
    Ub.create(description: "Centro de Saúde Padre Tarcisio")
    Ub.create(description: "Centro de Saúde Palmeiras")
    Ub.create(description: "Centro de Saúde Paraíso")
    Ub.create(description: "Centro de Saúde Pedreira Prado Lopes")
    Ub.create(description: "Centro de Saúde Pilar")
    Ub.create(description: "Centro de Saúde Pindorama")
    Ub.create(description: "Centro de Saúde Piratininga")
    Ub.create(description: "Centro de Saúde Pompeia")
    Ub.create(description: "Centro de Saúde Primeiro de Maio")
    Ub.create(description: "Centro de Saúde Professor Amilcar Viana Martins")
    Ub.create(description: "Centro de Saúde Providência")
    Ub.create(description: "Centro de Saúde Regina")
    Ub.create(description: "Centro de Saúde Ribeiro de Abreu")
    Ub.create(description: "Centro de Saúde Salgado Filho")
    Ub.create(description: "Centro de Saúde Santa Amélia")
    Ub.create(description: "Centro de Saúde Santa Cecília")
    Ub.create(description: "Centro de Saúde Santa Inés")
    Ub.create(description: "Centro de Saúde Santa Lúcia")
    Ub.create(description: "Centro de Saúde Santa Maria")
    Ub.create(description: "Centro de Saúde Santa Mônica")
    Ub.create(description: "Centro de Saúde Santa Rita de Cássia")
    Ub.create(description: "Centro de Saúde Santa Rosa")
    Ub.create(description: "Centro de Saúde Santa Terezinha")
    Ub.create(description: "Centro de Saúde Santo Antônio")
    Ub.create(description: "Centro de Saúde Santos Anjos")
    Ub.create(description: "Centro de Saúde São Bernardo")
    Ub.create(description: "Centro de Saúde São Cristovão")
    Ub.create(description: "Centro de Saúde São Francisco")
    Ub.create(description: "Centro de Saúde São Gabriel")
    Ub.create(description: "Centro de Saúde São Geraldo")
    Ub.create(description: "Centro de Saúde São Jorge")
    Ub.create(description: "Centro de Saúde São José")
    Ub.create(description: "Centro de Saúde São José Operário")
    Ub.create(description: "Centro de Saúde São Marcos")
    Ub.create(description: "Centro de Saúde São Miguel Arcanjo")
    Ub.create(description: "Centro de Saúde São Paulo")
    Ub.create(description: "Centro de Saúde São Tomás")
    Ub.create(description: "Centro de Saúde Serra Verde")
    Ub.create(description: "Centro de Saúde Serrano")
    Ub.create(description: "Centro de Saúde Taquaril")
    Ub.create(description: "Centro de Saúde Tia Amância")
    Ub.create(description: "Centro de Saúde Tirol")
    Ub.create(description: "Centro de Saúde Túnel de Ibirité")
    Ub.create(description: "Centro de Saúde Tupi")
    Ub.create(description: "Centro de Saúde Urucuia")
    Ub.create(description: "Centro de Saúde Vale do Jatobá")
    Ub.create(description: "Centro de Saúde Venda Nova")
    Ub.create(description: "Centro de Saúde Ventosa")
    Ub.create(description: "Centro de Saúde Vera Cruz")
    Ub.create(description: "Centro de Saúde Vila CEMIG")
    Ub.create(description: "Centro de Saúde Vila Leonina")
    Ub.create(description: "Centro de Saúde Vila Maria")
    Ub.create(description: "Centro de Saúde Vila Imperial")
    Ub.create(description: "Centro de Saúde Vila Pinho")
    Ub.create(description: "Centro de Saúde Vilas Reunidas")
    Ub.create(description: "Centro de Saúde Visconde do Rio Branco")
    Ub.create(description: "Centro de Saúde Vista Alegre")
    Ub.create(description: "Centro de Saúde Waldomiro Lobo")
  end
end