namespace :db do
  desc 'Criação de profissões'

  task create_professions: :environment do
    Profession.create(description: "Administrador de Banco de Dados")
    Profession.create(description: "Açougueiro")
    Profession.create(description: "Acompanhante de Idosos")
    Profession.create(description: "Acupunturista")
    Profession.create(description: "Administrador de Empresas")
    Profession.create(description: "Administrador de Redes")
    Profession.create(description: "Administrador de Sistemas")
    Profession.create(description: "Administrador Hospitalar")
    Profession.create(description: "Administrador Público")
    Profession.create(description: "Advogado")
    Profession.create(description: "Aeronauta")
    Profession.create(description: "Afiador de Ferramentas")
    Profession.create(description: "Agente Comunitário de Saúde")
    Profession.create(description: "Agente de Defesa Sanitária")
    Profession.create(description: "Agente de Viagens")
    Profession.create(description: "Agente Funerário")
    Profession.create(description: "Agente Penitenciário")
    Profession.create(description: "Agricultor")
    Profession.create(description: "Agrônomo")
    Profession.create(description: "Ajudante de Motorista")
    Profession.create(description: "Ajudante de Transportes")
    Profession.create(description: "Alfaiate")
    Profession.create(description: "Almirante")
    Profession.create(description: "Almoxarife")
    Profession.create(description: "Ambientalista")
    Profession.create(description: "Ambulante")
    Profession.create(description: "Analista Administrativo")
    Profession.create(description: "Analista Administrativo Financeiro")
    Profession.create(description: "Analista Ambiental")
    Profession.create(description: "Analista Comercial Interno")
    Profession.create(description: "Analista Comercial Externo")
    Profession.create(description: "Analista de Atendimento a Clientes")
    Profession.create(description: "Analista de Atendimento Comercial")
    Profession.create(description: "Analista de Banco")
    Profession.create(description: "Analista de Banco de Dados")
    Profession.create(description: "Analista de Cargos e Salários")
    Profession.create(description: "Analista de Cobrança")
    Profession.create(description: "Analista de Comércio Exterior")
    Profession.create(description: "Analista de Compras")
    Profession.create(description: "Analista de Comunicação")
    Profession.create(description: "Analista de Contabilidade")
    Profession.create(description: "Analista de Controladoria")
    Profession.create(description: "Analista de Controle de Qualidade")
    Profession.create(description: "Analista de Crédito e Cobrança")
    Profession.create(description: "Analista de Custos")
    Profession.create(description: "Analista de Departamento Pessoal")
    Profession.create(description: "Analista de Desenvolvimento de Produto")
    Profession.create(description: "Analista de Desenvolvimento de Sistemas")
    Profession.create(description: "Analista de Desenvolvimento Web")
    Profession.create(description: "Analista de Distribuição")
    Profession.create(description: "Analista de E-commerce")
    Profession.create(description: "Analista de Estoque")
    Profession.create(description: "Analista de Engenharia Elétrica")
    Profession.create(description: "Analista Financeiro")
    Profession.create(description: "Analista de Fiscal")
    Profession.create(description: "Analista Químico")
    Profession.create(description: "Anestesiologista")
    Profession.create(description: "Angiologista")
    Profession.create(description: "Antropólogo")
    Profession.create(description: "Apicultor")
    Profession.create(description: "Apresentador")
    Profession.create(description: "Argumentista")
    Profession.create(description: "Armador")
    Profession.create(description: "Armeiro")
    Profession.create(description: "Arquiteto")
    Profession.create(description: "Arquivista")
    Profession.create(description: "Arrumadeira")
    Profession.create(description: "Artista de Espetáculo de Diversões")
    Profession.create(description: "Artista Plástico")
    Profession.create(description: "Ascensorista")
    Profession.create(description: "Assessor de Imprensa")
    Profession.create(description: "Analista de Fundição")
    Profession.create(description: "Analista de Informática")
    Profession.create(description: "Analista de Investimentos")
    Profession.create(description: "Analista de Logística")
    Profession.create(description: "Analista de Loja")
    Profession.create(description: "Analista de Manutenção")
    Profession.create(description: "Analista de Manutenção Elétrica")
    Profession.create(description: "Analista de Marketing")
    Profession.create(description: "Analista de PCP")
    Profession.create(description: "Analista de Produção")
    Profession.create(description: "Analista de Programação")
    Profession.create(description: "Analista de Publicidade e Propaganda")
    Profession.create(description: "Analista de Qualidade")
    Profession.create(description: "Analista de Recrutamento e Seleção")
    Profession.create(description: "Analista de Recursos Humanos")
    Profession.create(description: "Analista de Redes")
    Profession.create(description: "Analista de Relações Públicas")
    Profession.create(description: "Analista de Representação Comercial")
    Profession.create(description: "Analista de SAC")
    Profession.create(description: "Analista de Segurança Patrimonial")
    Profession.create(description: "Analista de Seguros")
    Profession.create(description: "Analista de Sistemas")
    Profession.create(description: "Analista de Suporte Técnico")
    Profession.create(description: "Analista de Suprimentos")
    Profession.create(description: "Analista de Tecnologia da Informação (TI)")
    Profession.create(description: "Analista de Telecomunicações")
    Profession.create(description: "Analista de Telemarketing")
    Profession.create(description: "Analista de Tesouraria")
    Profession.create(description: "Analista de Transportes")
    Profession.create(description: "Analista de Treinamento")
    Profession.create(description: "Analista Econômico")
    Profession.create(description: "Assistente Comercial Interno")
    Profession.create(description: "Assistente de Almoxarifado")
    Profession.create(description: "Assistente de Arquitetura")
    Profession.create(description: "Assistente Administrativo")
    Profession.create(description: "Assistente de Atendimento a Clientes")
    Profession.create(description: "Assistente de Atendimento Comercial")
    Profession.create(description: "Assistente de Comércio Exterior")
    Profession.create(description: "Assistente de Compras")
    Profession.create(description: "Assistente de Comunicação")
    Profession.create(description: "Assistente de Contabilidade")
    Profession.create(description: "Assistente de Controladoria")
    Profession.create(description: "Assistente de Controle de Qualidade")
    Profession.create(description: "Assistente de Cozinha")
    Profession.create(description: "Assistente de Crédito e Cobrança")
    Profession.create(description: "Assistente de Custos")
    Profession.create(description: "Assistente de Departamento Pessoal")
    Profession.create(description: "Assistente de Desenvolvimento de Produto")
    Profession.create(description: "Assistente de Desenvolvimento de Sistemas")
    Profession.create(description: "Assistente de Distribuição")
    Profession.create(description: "Assistente de E-commerce")
    Profession.create(description: "Assistente de Enfermagem")
    Profession.create(description: "Assistente de Engenharia Elétrica")
    Profession.create(description: "Assistente de Estoque")
    Profession.create(description: "Assistente Financeiro")
    Profession.create(description: "Assistente de Informática")
    Profession.create(description: "Assistente de Jornalismo")
    Profession.create(description: "Assistente de Limpeza")
    Profession.create(description: "Assistente de Logística")
    Profession.create(description: "Assistente de Loja")
    Profession.create(description: "Assistente de Manutenção")
    Profession.create(description: "Assistente de Manutenção Elétrica")
    Profession.create(description: "Assistente de Marketing")
    Profession.create(description: "Assistente de PCP")
    Profession.create(description: "Assistente de Produção")
    Profession.create(description: "Assistente de Publicidade e Propaganda")
    Profession.create(description: "Assistente de Qualidade")
    Profession.create(description: "Assistente de Recrutamento e Seleção")
    Profession.create(description: "Assistente de Recursos Humanos")
    Profession.create(description: "Assistente de Representação Comercial")
    Profession.create(description: "Assistente de SAC")
    Profession.create(description: "Assistente de Seguros")
    Profession.create(description: "Assistente de Sistemas")
    Profession.create(description: "Assistente de Suporte Técnico")
    Profession.create(description: "Assistente de Suprimentos")
    Profession.create(description: "Assistente de Tecnologia da Informação (TI)")
    Profession.create(description: "Assistente de Telecomunicações")
    Profession.create(description: "Assistente de Telemarketing")
    Profession.create(description: "Assistente de Tesouraria")
    Profession.create(description: "Assistente de Transportes")
    Profession.create(description: "Assistente de Treinamento")
    Profession.create(description: "Assistente de Vendas Externas")
    Profession.create(description: "Assistente Editorial")
    Profession.create(description: "Assistente Fiscal")
    Profession.create(description: "Assistente Social")
    Profession.create(description: "Astrônomo")
    Profession.create(description: "Atendente")
    Profession.create(description: "Auditor")
    Profession.create(description: "Auxiliar de Almoxarifado")
    Profession.create(description: "Auxiliar de Almoxarife")
    Profession.create(description: "Auxiliar de Arquivo")
    Profession.create(description: "Auxiliar de Banco de Dados")
    Profession.create(description: "Auxiliar de Biblioteca")
    Profession.create(description: "Auxiliar de Comércio Exterior")
    Profession.create(description: "Auxiliar de Contabilidade")
    Profession.create(description: "Auxiliar de Controle de Qualidade")
    Profession.create(description: "Auxiliar de Cozinha")
    Profession.create(description: "Auxiliar de Crédito e Cobrança")
    Profession.create(description: "Auxiliar de Custos")
    Profession.create(description: "Auxiliar de Distribuição")
    Profession.create(description: "Auxiliar de Engenharia de Segurança do Trabalho")
    Profession.create(description: "Auviliar de Escritório")
    Profession.create(description: "Auxiliar de Fundição")
    Profession.create(description: "Auxiliar de Instalação")
    Profession.create(description: "Auxiliar de Limpeza")
    Profession.create(description: "Auxiliar de Manutenção Hidráulica")
    Profession.create(description: "Auxiliar de Padeiro")
    Profession.create(description: "Auxiliar de PCP")
    Profession.create(description: "Auxiliar de Programação")
    Profession.create(description: "Auxiliar de SAC")
    Profession.create(description: "Auxiliar de Segurança")
    Profession.create(description: "Auxiliar de Serralheiro")
    Profession.create(description: "Auxiliar de Suprimentos")
    Profession.create(description: "Auxiliar de Topografia")
    Profession.create(description: "Auxiliar de Transportes")
    Profession.create(description: "Auxiliar de Usinagem")
    Profession.create(description: "Auxiliar de Veterinária")
    Profession.create(description: "Auxiliar de Web Design")
    Profession.create(description: "Auxiliar Econômico")
    Profession.create(description: "Auxiliar Fiscal")
    Profession.create(description: "Auxiliar Jurídico")
    Profession.create(description: "Bartender")
    Profession.create(description: "Babá")
    Profession.create(description: "Balconista")
    Profession.create(description: "Bancário")
    Profession.create(description: "Barman")
    Profession.create(description: "Biblioteconista")
    Profession.create(description: "Biólogo")
    Profession.create(description: "Biomédico")
    Profession.create(description: "Bioquímico")
    Profession.create(description: "Biotecnólogo")
    Profession.create(description: "Bombeiro")
    Profession.create(description: "Borracheiro")
    Profession.create(description: "Cabeleireiro")
    Profession.create(description: "Cadista")
    Profession.create(description: "Cardiologista")
    Profession.create(description: "Cartazista")
    Profession.create(description: "Carteiro")
    Profession.create(description: "Cenógrafo")
    Profession.create(description: "Ceramista")
    Profession.create(description: "Cineasta")
    Profession.create(description: "Cinegrafista")
    Profession.create(description: "Cirurgião Plástico")
    Profession.create(description: "Clínico Geral")
    Profession.create(description: "Cobrador de Coletivo")
    Profession.create(description: "Comissário de Bordo")
    Profession.create(description: "Confeiteiro")
    Profession.create(description: "Conferente")
    Profession.create(description: "Consultor Contábil")
    Profession.create(description: "Consultor de Marketing")
    Profession.create(description: "Consultor de Moda")
    Profession.create(description: "Consultor de Qualidade")
    Profession.create(description: "Consultor de Vendas Externas")
    Profession.create(description: "Consultor de Viagens")
    Profession.create(description: "Contador")
    Profession.create(description: "Controlador de Tráfego")
    Profession.create(description: "Coordenador Administrativo")
    Profession.create(description: "Coordenador Comercial")
    Profession.create(description: "Coordenador de Almoxarifado")
    Profession.create(description: "Coordenador de Arquitetura")
    Profession.create(description: "Coordenador de Atendimento Comercial")
    Profession.create(description: "Coordenador de Atendimento a Clientes")
    Profession.create(description: "Coordenador de Banco")
    Profession.create(description: "Coordenador de Cargos e Salários")
    Profession.create(description: "Coordenador de Cobrança")
    Profession.create(description: "Coordenador de Comércio Exterior")
    Profession.create(description: "Coordenador de Compras")
    Profession.create(description: "Coordenador de Comunicação")
    Profession.create(description: "Coordenador de Contabilidade")
    Profession.create(description: "Coordenador de Controladoria")
    Profession.create(description: "Coordenador de Controle de Qualidade")
    Profession.create(description: "Coordenador de Cozinha")
    Profession.create(description: "Coordenador de Crédito e Cobrança")
    Profession.create(description: "Coordenador de Custos")
    Profession.create(description: "Coordenador de Departamento Pessoal")
    Profession.create(description: "Coordenador de Desenvolvimento de Produto")
    Profession.create(description: "Coordenador de Desenvolvimento de Sistemas")
    Profession.create(description: "Coordenador de Diagramação")
    Profession.create(description: "Coordenador de E-commerce")
    Profession.create(description: "Coordenador de Enfermagem")
    Profession.create(description: "Coordenador de Engenharia e Segurança do Trabalho")
    Profession.create(description: "Coordenador de Engenharia Elétrica")
    Profession.create(description: "Coordenador de Estoque")
    Profession.create(description: "Coordenador de Fundição")
    Profession.create(description: "Coordenador de Informática")
    Profession.create(description: "Coordenador de Jornalismo")
    Profession.create(description: "Coordenador de Limpeza")
    Profession.create(description: "Coordenador de Logística")
    Profession.create(description: "Coordenador de Loja")
    Profession.create(description: "Coordenador de Manutenção")
    Profession.create(description: "Coordenador de Manutenção Elétrica")
    Profession.create(description: "Coordenador de Marketing")
    Profession.create(description: "Coordenador de PCP")
    Profession.create(description: "Coordenador de Produção")
    Profession.create(description: "Coordenador de Publicidade e Propaganda")
    Profession.create(description: "Coordenador de Qualidade")
    Profession.create(description: "Coordenador de Recrutamento e Seleção")
    Profession.create(description: "Coordenador de Recursos Humanos")
    Profession.create(description: "Coordenador de Representação Comercial")
    Profession.create(description: "Coordenador de SAC")
    Profession.create(description: "Coordenador de Salão")
    Profession.create(description: "Coordenador de Segurança Patrimonial")
    Profession.create(description: "Coordenador de Seguros")
    Profession.create(description: "Coordenador de Sistemas")
    Profession.create(description: "Coordenador de Suporte Técnico")
    Profession.create(description: "Coordenador de Suprimentos")
    Profession.create(description: "Coordenador de Tecnologia da Informação")
    Profession.create(description: "Coordenador de Telecomunicações")
    Profession.create(description: "Coordenador de Telemarketing")
    Profession.create(description: "Coordenador de Tesouraraia")
    Profession.create(description: "Coordenador de Transportes")
    Profession.create(description: "Coordenador de Treinamento")
    Profession.create(description: "Coordenador de Usinagem")
    Profession.create(description: "Coordenador Econômico")
    Profession.create(description: "Coordenador Financeiro")
    Profession.create(description: "Coordenador Fiscal")
    Profession.create(description: "Coordenador Químico")
    Profession.create(description: "Corretor de Seguros")
    Profession.create(description: "Cozinheiro")
    Profession.create(description: "Diretor Administrativo")
    Profession.create(description: "Dentista")
    Profession.create(description: "Desenhista")
    Profession.create(description: "Designer de Interiores")
    Profession.create(description: "Designer de Moda")
    Profession.create(description: "Diagramador")
    Profession.create(description: "Diretor Comercial")
    Profession.create(description: "Diretor de Cinema")
    Profession.create(description: "Diretor de Prdução")
    Profession.create(description: "Diretor de Representação Comercial")
    Profession.create(description: "Diretor de Recursos Humanos")
    Profession.create(description: "Diretor de Tecnologia da Informação (TI)")
    Profession.create(description: "Diretor de Marketing")
    Profession.create(description: "Diretor Financeiro")
    Profession.create(description: "Diretor de Informática")
    Profession.create(description: "Diretor de Jornalismo")
    Profession.create(description: "Diretor de Suporte Técnico")
    Profession.create(description: "Diretor de Logística")
    Profession.create(description: "Diretor de Departamento Pessoal")
    Profession.create(description: "Ecologista")
    Profession.create(description: "Economista")
    Profession.create(description: "Editor")
    Profession.create(description: "Educador")
    Profession.create(description: "Eletricista")
    Profession.create(description: "Eletricista de Manutenção")
    Profession.create(description: "Embalador")
    Profession.create(description: "Empreagdo (a) Doméstico (a)")
    Profession.create(description: "Encanador")
    Profession.create(description: "Encarregado de Almoxarifado")
    Profession.create(description: "Encarregado de PCP")
    Profession.create(description: "Encarregado de Recursos Humanos")
    Profession.create(description: "Encarregado de Segurança")
    Profession.create(description: "Encarregado de Transporte")
    Profession.create(description: "Encarregado de Usinagem")
    Profession.create(description: "Endocrinologista")
    Profession.create(description: "Engenheiro Têxtil")
    Profession.create(description: "Enfermeiro")
    Profession.create(description: "Engenheiro Aeronáutico")
    Profession.create(description: "Engenheiro Agrimensor")
    Profession.create(description: "Engenheiro Agrônomo")
    Profession.create(description: "Engenheiro Ambiental")
    Profession.create(description: "Engenheiro Civil")
    Profession.create(description: "Engenheiro da Computação")
    Profession.create(description: "Engenheiro de Alimentos")
    Profession.create(description: "Engenheiro de Engenharia e Segurança do Trabalho")
    Profession.create(description: "Engenheiro de Produção")
    Profession.create(description: "Engenheiro de Suprimentos")
    Profession.create(description: "Engenheiro de Telecomunicações")
    Profession.create(description: "Engenheiro Eletricista")
    Profession.create(description: "Engenheiro Metalúrgico")
    Profession.create(description: "Engenheiro Naval")
    Profession.create(description: "Engenheiro Nuclear")
    Profession.create(description: "Estagiário")
    Profession.create(description: "Esteticista")
    Profession.create(description: "Estilista")
    Profession.create(description: "Estoquista")
    Profession.create(description: "Estudante")
    Profession.create(description: "Fundidor")
    Profession.create(description: "Farmacêutico")
    Profession.create(description: "Feirante")
    Profession.create(description: "Filósofo")
    Profession.create(description: "Físico")
    Profession.create(description: "Fisioterapeuta")
    Profession.create(description: "Fonoaudiólogo")
    Profession.create(description: "Fotógrafo")
    Profession.create(description: "Fresador")
    Profession.create(description: "Garçom")
    Profession.create(description: "Gari")
    Profession.create(description: "Gastrônomo")
    Profession.create(description: "Geofísico")
    Profession.create(description: "Geográfo")
    Profession.create(description: "Geólogo")
    Profession.create(description: "Gerente Administrativo")
    Profession.create(description: "Gerente Comercial")
    Profession.create(description: "Gerente de Atendimento a Clientes")
    Profession.create(description: "Gerente de Atendimento Comercial")
    Profession.create(description: "Gerente de Banco")
    Profession.create(description: "Gerente de Cobrança")
    Profession.create(description: "Gerente de Comércio Exterior")
    Profession.create(description: "Gerente de Compras")
    Profession.create(description: "Gerente de Comunicação")
    Profession.create(description: "Gerente de Contabilidade")
    Profession.create(description: "Gerente de Contas")
    Profession.create(description: "Gerente de Controladoria")
    Profession.create(description: "Gerente de Controle de Qualidade")
    Profession.create(description: "Gerente de Cozinha")
    Profession.create(description: "Gerente de Departamento Pessoal")
    Profession.create(description: "Gerente de Desenvolvimento de Produto")
    Profession.create(description: "Gerente de Desenvolvimento de Sistemas")
    Profession.create(description: "Gerente de Distribuição")
    Profession.create(description: "Gerente de E-commerce")
    Profession.create(description: "Gerente de Enfermagem")
    Profession.create(description: "Gerente de Engenharia Elétrica")
    Profession.create(description: "Gerente de Estoque")
    Profession.create(description: "Gerente de Hotelaria")
    Profession.create(description: "Gerente de Informática")
    Profession.create(description: "Gerente de Jornalismo")
    Profession.create(description: "Gerente de Logística")
    Profession.create(description: "Gerente de Loja")
    Profession.create(description: "Gerente de Manutenção")
    Profession.create(description: "Gerente de Manutenção Elétrica")
    Profession.create(description: "Gerente de Marketing")
    Profession.create(description: "Gerente de PCP")
    Profession.create(description: "Gerente de Produção")
    Profession.create(description: "Gerente de Publicidade e Propaganda")
    Profession.create(description: "Gerente de Qualidade")
    Profession.create(description: "Gerente de Recrutamento e Seleção")
    Profession.create(description: "Gerente de Recursos Humanos")
    Profession.create(description: "Gerente de Representação Comercial")
    Profession.create(description: "Gerente de SAC")
    Profession.create(description: "Gerente de Salão")
    Profession.create(description: "Gerente de Segurança Patrimonial")
    Profession.create(description: "Gerente de Seguros")
    Profession.create(description: "Gerente de Sistemas")
    Profession.create(description: "Gerente de Suporte Técnico")
    Profession.create(description: "Gerente de Suprimentos")
    Profession.create(description: "Gerente de Tecnologia da Informação (TI)")
    Profession.create(description: "Gerente de Telecomunicações")
    Profession.create(description: "Gerente de Telemarketing")
    Profession.create(description: "Gerente de Tesouraria")
    Profession.create(description: "Gerente de Transportes")
    Profession.create(description: "Gerente Financeiro")
    Profession.create(description: "Gerente Fiscal")
    Profession.create(description: "Gerente Químico")
    Profession.create(description: "Geriatra")
    Profession.create(description: "Gestor Ambiental")
    Profession.create(description: "Ginecologista")
    Profession.create(description: "Governanta")
    Profession.create(description: "Homeopata")
    Profession.create(description: "Historiador")
    Profession.create(description: "Inspetor de Controle de Qualidade")
    Profession.create(description: "Instalador de Acessórios Automotivos")
    Profession.create(description: "Instalador de Alarmes")
    Profession.create(description: "Instalador de Cabeamento Estruturado")
    Profession.create(description: "Instalador de Telecomunicações")
    Profession.create(description: "Instrutor de Treinamento")
    Profession.create(description: "Jornalista")
    Profession.create(description: "Jardineiro")
    Profession.create(description: "Lavrador")
    Profession.create(description: "Líder de Produção")
    Profession.create(description: "Líder de Usinagem")
    Profession.create(description: "Locutor")
    Profession.create(description: " Maestro")
    Profession.create(description: "Mandrilhador")
    Profession.create(description: "Manicure/Pedicure")
    Profession.create(description: "Manobrista")
    Profession.create(description: "Maquiador")
    Profession.create(description: "Marceneiro")
    Profession.create(description: "Marinheiro")
    Profession.create(description: "Matemático")
    Profession.create(description: "Mecânico")
    Profession.create(description: "Mecânico de Automóveis")
    Profession.create(description: "Mecânico de Manutenção Hidráulica")
    Profession.create(description: "Médico")
    Profession.create(description: "Mestre-de-Obras")
    Profession.create(description: "Modelo")
    Profession.create(description: "Monitor de Atendimento a Clientes")
    Profession.create(description: "Monitor de Telemarketing Ativo")
    Profession.create(description: "Monitor de Telemarketing Receptivo")
    Profession.create(description: "Motoboy")
    Profession.create(description: "Motorista")
    Profession.create(description: "Neurologista")
    Profession.create(description: "Nutricionista")
    Profession.create(description: "Obstetra")
    Profession.create(description: "Oftalmologista")
    Profession.create(description: "Operador de Atendimento a Clientes")
    Profession.create(description: "Operador de Caixa")
    Profession.create(description: "Operador de Fundição")
    Profession.create(description: "Operador de Guilhotina")
    Profession.create(description: "Operador de Logística")
    Profession.create(description: "Operador de Produção")
    Profession.create(description: "Operador de SAC")
    Profession.create(description: "Operador de Telemarketing Ativo")
    Profession.create(description: "Operador de Telemarketing Receptivo")
    Profession.create(description: "Operador de Torno")
    Profession.create(description: "Operador de Usinagem")
    Profession.create(description: "Ortopedista")
    Profession.create(description: "Otorrinolaringologista")
    Profession.create(description: "Psicólogo")
    Profession.create(description: "Padeiro")
    Profession.create(description: "Padre")
    Profession.create(description: "Paisagista")
    Profession.create(description: "Pastor")
    Profession.create(description: "Pescador")
    Profession.create(description: "Pediatra")
    Profession.create(description: "Pedreiro")
    Profession.create(description: "Pintor")
    Profession.create(description: "Podólogo")
    Profession.create(description: "Polidor")
    Profession.create(description: "Produtor Editorial")
    Profession.create(description: "Professor")
    Profession.create(description: "Programador")
    Profession.create(description: "Promotor Bancário")
    Profession.create(description: "Químico")
    Profession.create(description: "Radialista")
    Profession.create(description: "Radiologista")
    Profession.create(description: "Recepcionista")
    Profession.create(description: "Redator")
    Profession.create(description: "Repórter")
    Profession.create(description: "Representante Comercial")
    Profession.create(description: "Supervisor Administrativo")
    Profession.create(description: "Secretária")
    Profession.create(description: "Serralheiro")
    Profession.create(description: "Supervisor Comercial")
    Profession.create(description: "Supervisor de Almoxarifado")
    Profession.create(description: "Supervisor de Atendimento a Clientes")
    Profession.create(description: "Supervisor de Atendimento Comercial")
    Profession.create(description: "Supervisor de Banco")
    Profession.create(description: "Supervisor de Cargos e Salários")
    Profession.create(description: "Supervisor de Cobrança")
    Profession.create(description: "Supervisor de Comércio Exterior")
    Profession.create(description: "Supervisor de Compras")
    Profession.create(description: "Supervisor de Comunicação")
    Profession.create(description: "Supervisor de Contabilidade")
    Profession.create(description: "Supervisor de Controladoria")
    Profession.create(description: "Supervisor de Controle de Qualidade")
    Profession.create(description: "Supervisor de Cozinha")
    Profession.create(description: "Supervisor de Crédito e Cobrança")
    Profession.create(description: "Supervisor de Custos")
    Profession.create(description: "Supervisor de Departamento Pessoal")
    Profession.create(description: "Supervisor de Desenvolvimento de Produto")
    Profession.create(description: "Supervisor de Desenvolvimento de Sistemas")
    Profession.create(description: "Supervisor de Distribuição")
    Profession.create(description: "Supervisor de E-commerce")
    Profession.create(description: "Supervisor de Enfermagem")
    Profession.create(description: "Supervisor de Engenharia e Segurança do Trabalho")
    Profession.create(description: "Supervisor de Engenharia Elétrica")
    Profession.create(description: "Supervisor de Estoque")
    Profession.create(description: "Supervisor de Fundição")
    Profession.create(description: "Supervisor de Informática")
    Profession.create(description: "Supervisor de Limpeza")
    Profession.create(description: "Supervisor de Logística")
    Profession.create(description: "Supervisor de Loja")
    Profession.create(description: "Supervisor de Manutenção")
    Profession.create(description: "Supervisor de Marketing")
    Profession.create(description: "Supervisor de Manutenção Elétrica")
    Profession.create(description: "Supervisor de PCP")
    Profession.create(description: "Supervisor de Produção")
    Profession.create(description: "Supervisor de Publicidade e Propaganda")
    Profession.create(description: "Supervisor de Qualidade")
    Profession.create(description: "Supervisor de Recrutamento e Seleção")
    Profession.create(description: "Supervisor de Recursos Humanos")
    Profession.create(description: "Supervisor de Representação Comercial")
    Profession.create(description: "Supervisor de SAC")
    Profession.create(description: "Supervisor de Salão")
    Profession.create(description: "Supervisor de Segurança")
    Profession.create(description: "Supervisor de Segurança Patrimonial")
    Profession.create(description: "Supervisor de Seguros")
    Profession.create(description: "Supervisor de Sistemas")
    Profession.create(description: "Supervisor de Suporte Técnico")
    Profession.create(description: "Supervisor de Suprimentos")
    Profession.create(description: "Supervisor de Tecnologia da Informação (TI)")
    Profession.create(description: "Supervisor de Telecomunicações")
    Profession.create(description: "Supervisor de Telemarketing")
    Profession.create(description: "Supervisor de Tesouraria")
    Profession.create(description: "Supervisor de Transportes")
    Profession.create(description: "Supervisor de Usinagem")
    Profession.create(description: "Supervisor Econômico")
    Profession.create(description: "Supervisor Fiscal")
    Profession.create(description: "Técnico Ambiental")
    Profession.create(description: "Técnico de Controle de Qualidade")
    Profession.create(description: "Técnico de Edificações")
    Profession.create(description: "Técnico de Suporte")
    Profession.create(description: "Técnico em Manutenção Elétrica")
    Profession.create(description: "Técnico em Análise Clínica")
    Profession.create(description: "Técnico em Análise Química")
    Profession.create(description: "Técnico em Automação")
    Profession.create(description: "Técnico em Guia de Turismo")
    Profession.create(description: "Técnico em Hardware")
    Profession.create(description: "Técnico em Metalúrgica")
    Profession.create(description: "Técnico em Redes")
    Profession.create(description: "Técnico em Secretariado")
    Profession.create(description: "Técnico em Secretariado Escolar")
    Profession.create(description: "Técnico em Transações Imobiliárias")
    Profession.create(description: "Técnico em Zootecnia")
    Profession.create(description: "Técnico Instalador")
    Profession.create(description: "Técnico em Telecomunicações")
    Profession.create(description: "Tesoureiro")
    Profession.create(description: "Topógrafo")
    Profession.create(description: "Tradutor")
    Profession.create(description: "Traumatologista")
    Profession.create(description: "Turismólogo")
    Profession.create(description: "Urologista")
    Profession.create(description: "Vendedor")
    Profession.create(description: "Veterinário")
    Profession.create(description: "Vigilante")
    Profession.create(description: "Vigilante")
    Profession.create(description: "Vitrinista")
    Profession.create(description: "Web Design")
    Profession.create(description: "Zelador")
    Profession.create(description: "Zootecnista")
  end
end